[Thread-4] WEBORB ERROR:28/11/2009 10:03:23:Db4objects.Db4o.Ext.DatabaseClosedException: Exception of type 'Db4objects.Db4o.Ext.DatabaseClosedException' was thrown.
   at Db4objects.Db4o.Internal.ObjectContainerBase.CheckClosed()
   at Db4objects.Db4o.Internal.Query.Result.AbstractQueryResult.Lock()
   at Db4objects.Db4o.Internal.Query.Result.StatefulQueryResult.Lock()
   at Db4objects.Db4o.Internal.Query.Result.StatefulQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.GenericObjectSetFacade`1.get_Item(Int32 index)
   at SDE.CamadaControle.CItem.LoadAliquotas(Int32 idEmp, Int32 idItem)
   at SDE.MetodoCorretivo.MetodoCorretivo.certificaItemEmpAliquotas()
   at SDE.MetodoCorretivo.MetodoCorretivo.metodoCorretivo()
   at SDE.CamadaServico.SBancoDados.MetodoCorretivo()
[Thread-4] WEBORB ERROR:28/11/2009 10:11:14:Db4objects.Db4o.Ext.DatabaseClosedException: Exception of type 'Db4objects.Db4o.Ext.DatabaseClosedException' was thrown.
   at Db4objects.Db4o.Internal.ObjectContainerBase.CheckClosed()
   at Db4objects.Db4o.Internal.Query.Result.AbstractQueryResult.Lock()
   at Db4objects.Db4o.Internal.Query.Result.StatefulQueryResult.Lock()
   at Db4objects.Db4o.Internal.Query.Result.StatefulQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.GenericObjectSetFacade`1.get_Item(Int32 index)
   at SDE.CamadaControle.CItem.LoadAliquotas(Int32 idEmp, Int32 idItem)
   at SDE.MetodoCorretivo.MetodoCorretivo.certificaItemEmpAliquotas()
   at SDE.MetodoCorretivo.MetodoCorretivo.metodoCorretivo()
   at SDE.CamadaServico.SBancoDados.MetodoCorretivo()
[Thread-4] WEBORB ERROR:28/11/2009 10:44:49:System.Exception: [erro anotado 2] Index was outside the bounds of the array.    at Db4objects.Db4o.Internal.Query.Result.IdListQueryResult.GetId(Int32 index)
   at Db4objects.Db4o.Internal.Query.Result.IdListQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.Result.StatefulQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.ObjectSetFacade.get_Item(Int32 index)
   at SDE.CamadaNuvem.NuvemModificacoes.Tecnico_certificaItemEmpAliquotas(Int32 idCorp, Int32 idEmp) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Tecnico.cs:line 78 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Db4objects.Db4o.Internal.Query.Result.IdListQueryResult.GetId(Int32 index)
   at Db4objects.Db4o.Internal.Query.Result.IdListQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.Result.StatefulQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.ObjectSetFacade.get_Item(Int32 index)
   at SDE.CamadaNuvem.NuvemModificacoes.Tecnico_certificaItemEmpAliquotas(Int32 idCorp, Int32 idEmp) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Tecnico.cs:line 78
   --- End of inner exception stack trace ---
   at SDE.CamadaNuvem.SuperNuvem.dbRollback(Exception ex, IObjectContainer[] dbList) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\SuperNuvem.cs:line 65
   at SDE.CamadaNuvem.NuvemModificacoes.Tecnico_certificaItemEmpAliquotas(Int32 idCorp, Int32 idEmp) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Tecnico.cs:line 103
