[Thread-4] WEBORB ERROR:22/12/2009 08:45:24:System.Exception: [erro anotado 2] Index was outside the bounds of the array.    at Db4objects.Db4o.Internal.Query.Result.IdListQueryResult.GetId(Int32 index)
   at Db4objects.Db4o.Internal.Query.Result.IdListQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.Result.StatefulQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.ObjectSetFacade.get_Item(Int32 index)
   at SDE.CamadaNuvem.NuvemModificacoes.GerarTXT(Int32 idCorp, Int32 idEmp, Mov mov_dados, MovNFE mov_nfe_dados, MovNfeVeiculo mov_nfe_vei_dados, List`1 mItens_dados) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Nfe.cs:line 141 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Db4objects.Db4o.Internal.Query.Result.IdListQueryResult.GetId(Int32 index)
   at Db4objects.Db4o.Internal.Query.Result.IdListQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.Result.StatefulQueryResult.Get(Int32 index)
   at Db4objects.Db4o.Internal.Query.ObjectSetFacade.get_Item(Int32 index)
   at SDE.CamadaNuvem.NuvemModificacoes.GerarTXT(Int32 idCorp, Int32 idEmp, Mov mov_dados, MovNFE mov_nfe_dados, MovNfeVeiculo mov_nfe_vei_dados, List`1 mItens_dados) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Nfe.cs:line 141
   --- End of inner exception stack trace ---
   at SDE.CamadaNuvem.SuperNuvem.dbRollback(Exception ex, IObjectContainer[] dbList) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\SuperNuvem.cs:line 65
   at SDE.CamadaNuvem.NuvemModificacoes.GerarTXT(Int32 idCorp, Int32 idEmp, Mov mov_dados, MovNFE mov_nfe_dados, MovNfeVeiculo mov_nfe_vei_dados, List`1 mItens_dados) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Nfe.cs:line 265
[Thread-4] WEBORB ERROR:22/12/2009 08:51:32:System.Exception: [erro anotado 2] Object reference not set to an instance of an object.    at SDE.EntidadeNFE.EscreveItensNfeTXT.Escreve_transp(StringBuilder sb, Cliente cli, ClienteEndereco ce, ClienteVeiculo veiculo, ClienteVeiculo reboque, MovNFE nfe) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\EntidadeNFE\EscreveItensNfeTXT.cs:line 690
   at SDE.CamadaNuvem.NuvemModificacoes.GerarTXT(Int32 idCorp, Int32 idEmp, Mov mov_dados, MovNFE mov_nfe_dados, MovNfeVeiculo mov_nfe_vei_dados, List`1 mItens_dados) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Nfe.cs:line 249 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at SDE.EntidadeNFE.EscreveItensNfeTXT.Escreve_transp(StringBuilder sb, Cliente cli, ClienteEndereco ce, ClienteVeiculo veiculo, ClienteVeiculo reboque, MovNFE nfe) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\EntidadeNFE\EscreveItensNfeTXT.cs:line 690
   at SDE.CamadaNuvem.NuvemModificacoes.GerarTXT(Int32 idCorp, Int32 idEmp, Mov mov_dados, MovNFE mov_nfe_dados, MovNfeVeiculo mov_nfe_vei_dados, List`1 mItens_dados) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Nfe.cs:line 249
   --- End of inner exception stack trace ---
   at SDE.CamadaNuvem.SuperNuvem.dbRollback(Exception ex, IObjectContainer[] dbList) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\SuperNuvem.cs:line 65
   at SDE.CamadaNuvem.NuvemModificacoes.GerarTXT(Int32 idCorp, Int32 idEmp, Mov mov_dados, MovNFE mov_nfe_dados, MovNfeVeiculo mov_nfe_vei_dados, List`1 mItens_dados) in C:\dev\sistemadaempresa\ambiente_desenvolvimento\marcos\lado_servidor\sde_marcos\SDE\code\CamadaNuvem\NuvemModificacoes_Nfe.cs:line 269
[Thread-11] WEBORB ERROR:22/12/2009 08:54:01:An item with the same key has already been added.    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Weborb.Util.License.LicenseManager.GetInstance(Int32 productID)
   at Weborb.Util.Invocation.invoke(Object obj, MethodInfo method, Object[] arguments)
   at Weborb.Handler.ObjectHandler.invoke(String typeName, String function, Object[] arguments, RequestContext context)
